services:
  pdf-copilot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma_db
      - UPLOAD_DIR=/app/data/uploads
      - DEBUG=false
    depends_on:
      - ollama
    networks:
      - pdf-copilot-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    networks:
      - pdf-copilot-network

volumes:
  ollama_data:

networks:
  pdf-copilot-network:
    driver: bridge
